let messageEndings1 = ["a new adventure.","a breakthrough.","greatness.","wisely.","abundance."]
let messageEndings2 = ["resilient.","the light.","steadfast.","the master of your fate.","a force of nature."]
let messageEndings3 = ["calm.","clarity.","strength.","purpose.","healing."]
let messageEndings4 = ["opportunity.","growth.","a new beginning.","purpose.","healing."]
let messageEndings5 = ["your favor.","to success.","endless possibilities.","into your life.","prosperity."]